# Generated by Django 2.1.7 on 2019-03-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=500, verbose_name='ФИО клиента')),
                ('datetime', models.DateTimeField(verbose_name='Время записи')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CarModel', verbose_name='Марка автомобиля')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Запись на диагностику',
                'verbose_name_plural': 'Записи на диагностику',
            },
        ),
    ]
